name: Market Automation

on:
  schedule:
  - cron: '5 7-15/0 * * 1-5'
  - cron: '20 7-15/0 * * 1-5'
  - cron: '35 7-15/0 * * 1-5'
  - cron: '50 7-15/0 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests
          pip install git+https://github.com/rongardF/tvdatafeed.git

      - name: Run bot
        run: python market_bot.py
